server:
       port: 8080
#       servlet:
#               context-path: /mhmall-frontend2
       contextPath: /mhmall-frontend2


spring:
       profiles:
                active: dev
       devtools:
                livereload:
                           enabled: true
       http:
            encoding:
                     charset: UTF-8
                     enabled: true
                     forced: true
                     forced-request: true
                     forced-response: true
       aop:
           auto: true
       aop-proxy-target-class: true
       application:
           name: front-end-server
       servlet:
           multipart:
               enabled:true
               max-file-size:50MB
               max-request-size:50MB
       zipkin:
           baseUrl: http://192.168.0.10:9411/
       sleuth:
           enabled: true
           sampler:
               probability: 1.0
sample:
  zipkin:
    enabled: true
