server:
       port: 8888
#       servlet:
#               context-path: /mhmall
       contextPath: /mhmall


spring:
       profiles:
                active: dev
       devtools:
                livereload:
                           enabled: true
       http:
            encoding:
                     charset: UTF-8
                     enabled: true
                     forced: true
                     forced-request: true
                     forced-response: true
       aop:
           auto: true
       aop-proxy-target-class: true
       datasource:
              driverClassName: org.mariadb.jdbc.Driver
              url: jdbc:mariadb://192.168.0.10:3307/mshop?allowMultiQueries=true&amp;sql_safe_updates=0
              username: mshop
              password: mshop
       application:
           name: back-end-server
       servlet:
           multipart:
               enabled:true
               max-file-size:50MB
               max-request-size:50MB
       zipkin:
           baseUrl: http://192.168.0.10:9411/
       sleuth:
           enabled: true
       sampler:
           probability: 1.0
sample:
  zipkin:
    enabled: true
mybatis:
       config-location: classpath:mybatis/configuration.xml

